### ISSUE TITLE
Working with 54622D, too

### ISSUE THREAD

**Issue by xunker** [kiwih/agilent-rs232#2]
Although it's expected, still wanted to confirm to you that this is all working on my 54622D (same as '21A, but 100mhz and adds 16ch logic analyzer). I'm in the same boat as you, having picked it up from the scrap heap and not wanting to deal with floppy disks, so this is a real benefit! Thanks!

**Comment by kiwih** [comment]
Glad to hear it! I added a note to the README. Cheers!
